#!/usr/bin/env bash
# Delete existing lab containers and recreate per NODE_SPEC.md
set -euo pipefail
LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${LAB_DIR}"

DOCKER="${DOCKER:-sudo docker}"
COMPOSE=(${DOCKER} compose)

echo "==> Removing old redis-related containers (if any)"
for name in redis-n1 redis-n2 redis-n3 docker-node; do
  ${DOCKER} rm -f "${name}" 2>/dev/null || true
done

# Also tear down compose project volumes for clean cluster state
${COMPOSE[@]} down -v --remove-orphans 2>/dev/null || true

echo "==> Building images (Redis nodes + inject node)"
${COMPOSE[@]} build --pull

echo "==> Starting 4 nodes"
${COMPOSE[@]} up -d

echo "==> Verifying memory limits on Redis nodes"
for ctn in redis-n1 redis-n2 redis-n3; do
  mem="$(${DOCKER} inspect -f '{{.HostConfig.Memory}}' "${ctn}" 2>/dev/null || echo 0)"
  if [[ "${mem}" =~ ^[0-9]+$ ]] && [[ "${mem}" -gt 0 ]]; then
    echo "  ${ctn} mem_limit=$((mem / 1024 / 1024))MB"
  else
    echo "  WARN: ${ctn} has no mem_limit — run compose with mem_limit: 1536m for F04"
  fi
done

echo "==> Ensuring container-to-container FORWARD is allowed"
if command -v modprobe >/dev/null 2>&1; then
  modprobe sch_netem 2>/dev/null || sudo modprobe sch_netem 2>/dev/null || \
    echo "WARN: sch_netem not loaded; F22 packet-loss needs it on Docker host"
fi
# Some hosts have iptables-legacy FORWARD DROP which breaks ICC
if command -v iptables-legacy >/dev/null 2>&1; then
  iptables-legacy -P FORWARD ACCEPT 2>/dev/null || sudo iptables-legacy -P FORWARD ACCEPT 2>/dev/null || true
  iptables-legacy -C FORWARD -j ACCEPT 2>/dev/null || iptables-legacy -I FORWARD -j ACCEPT 2>/dev/null \
    || sudo iptables-legacy -I FORWARD -j ACCEPT 2>/dev/null || true
fi
${DOCKER} exec -u root "$(${DOCKER} ps -q | head -1)" true >/dev/null 2>&1 || true

echo "==> Waiting for Redis PING"
for ip in 10.10.26.144 10.10.26.145 10.10.26.146; do
  ok=0
  for _ in $(seq 1 30); do
    if ${DOCKER} exec docker-node redis-cli -h "${ip}" -p 6379 -a 'Redis@1314' --no-auth-warning PING 2>/dev/null | grep -q PONG; then
      echo "  PONG ${ip}:6379"
      ok=1
      break
    fi
    sleep 1
  done
  [[ "${ok}" -eq 1 ]] || { echo "FAIL: Redis not up on ${ip}"; exit 1; }
done

echo "==> Creating 3-master cluster (replicas=0)"
${DOCKER} exec docker-node redis-cli -a 'Redis@1314' --no-auth-warning --cluster create \
  10.10.26.144:6379 10.10.26.145:6379 10.10.26.146:6379 \
  --cluster-replicas 0 --cluster-yes

echo "==> Verifying NODE_SPEC tools on Redis nodes"
for ctn in redis-n1 redis-n2 redis-n3; do
  ${DOCKER} exec "${ctn}" bash -lc 'command -v stress-ng && command -v vmstat && command -v chmod && command -v dd && command -v iptables && command -v tc'
  echo "  OK tools in ${ctn}"
done

echo "==> Verifying inject tools on docker-node"
${DOCKER} exec docker-node bash -lc 'bash --version | head -1; redis-cli --version; flock --version | head -1; docker --version'

echo "==> Writing lab config.env for scripts"
cat > "${LAB_DIR}/../config.env" <<'EOF'
# Generated by lab/recreate.sh — gitignored
export INJECT_BACKEND="docker"
export REDIS_NODES="10.10.26.144:6379 10.10.26.145:6379 10.10.26.146:6379"
export REDIS_PASSWORD="Redis@1314"
export REDIS_CLI="redis-cli"
export CLUSTER_BUS_PORT=16379
export FAULT_DURATION_SEC=600
export REDIS_CONTAINER_MAP="10.10.26.144:redis-n1 10.10.26.145:redis-n2 10.10.26.146:redis-n3"
export REDIS_DATA_DIR="auto"
export REDIS_CONF="/usr/local/etc/redis/redis.conf"
export REDIS_SERVICE="redis"
export REDIS_ACL_USER="default"
export MISCONF_CLEANUP_RESTART="YES"
export SSH_USER="root"
export TARGET_HOST=""
EOF

echo "==> Running preflight inside docker-node"
${DOCKER} exec docker-node bash -lc 'cd /workspace/redis_fault_injection && chmod +x run.sh scripts/*.sh lib/common.sh lab/recreate.sh && ./scripts/preflight.sh'

echo "==> Lab ready"
${DOCKER} ps --format 'table {{.Names}}\t{{.Status}}\t{{.Networks}}' | grep -E 'NAMES|redis-n|docker-node' || ${DOCKER} ps
