# Lab Redis node config — binary redis in container (simulated VM)
bind 0.0.0.0
port 6379
dir /var/lib/redis/6379
dbfilename dump.rdb
appendonly yes
appendfilename appendonly.aof

protected-mode no
requirepass Redis@1314
masterauth Redis@1314

cluster-enabled yes
cluster-config-file nodes-6379.conf
cluster-node-timeout 5000
cluster-announce-port 6379
cluster-announce-bus-port 16379

# Allow DEBUG SLEEP for F14
enable-debug-command yes

daemonize no
logfile ""
save ""
